/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import domain.Estudiantes;
import domain.Notas;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import service.ArchivoService;
import service.CalculoService;
import service.RegistroEstudianteService;

/**
 *
 * @author Rogelis Garcia
 */
public class RegistroEstudiantesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroEstudiantesFrame.class.getName());

    /**
     * Creates new form RegistroEstudiantesFrame
     */
    public RegistroEstudiantesFrame() {
        initComponents();
    }
    
    
    RegistroEstudianteService registro = new RegistroEstudianteService();
    CalculoService calculo = new CalculoService();

    public void ActualizarListaEstudiantes() {
        var modelo = (javax.swing.table.DefaultTableModel) JTabla.getModel(); //obtenemos modelos de la tabla 
        modelo.setNumRows(0); //inicializa en 0
        for (var e : registro.ListarEstudiantes()) {
            modelo.addRow(new Object[]{
                e.getNombre(),
                e.getEdad(),
                e.getNotas().get(0).getValor(),
                e.getNotas().get(1).getValor(),
                e.getNotas().get(2).getValor()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();
        titutoEdad = new javax.swing.JLabel();
        titutoN1 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        tituloN2 = new javax.swing.JLabel();
        SetCSV = new javax.swing.JButton();
        tituloN3 = new javax.swing.JLabel();
        GetCSV = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        JButtonCerrarLogin = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        txtNota1 = new javax.swing.JTextField();
        lbPromedio = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        lbMaximo = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        lbResultado = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        SpinnerEdad = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloNombre.setText("Nombre:");

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Nota 1", "Nota 2", "Nota 3"
            }
        ));
        JTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JTabla);

        titutoEdad.setText("Edad:");

        titutoN1.setText("Nota 1:");

        Guardar.setBackground(new java.awt.Color(0, 204, 51));
        Guardar.setText("Guardar");
        Guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        tituloN2.setText("Nota 2:");

        SetCSV.setBackground(new java.awt.Color(204, 204, 204));
        SetCSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SetCSV.setText("Cargar CSV");
        SetCSV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SetCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetCSVActionPerformed(evt);
            }
        });

        tituloN3.setText("Nota 3:");

        GetCSV.setBackground(new java.awt.Color(204, 204, 204));
        GetCSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GetCSV.setText("Guardar CSV");
        GetCSV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GetCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCSVActionPerformed(evt);
            }
        });

        calcular.setBackground(new java.awt.Color(0, 0, 153));
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("Calcular");
        calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        JButtonCerrarLogin.setBackground(new java.awt.Color(204, 204, 204));
        JButtonCerrarLogin.setText("Cerrar Sesion");
        JButtonCerrarLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JButtonCerrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCerrarLoginActionPerformed(evt);
            }
        });

        limpiar.setBackground(new java.awt.Color(153, 0, 0));
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("Limpiar");
        limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        lbPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPromedio.setText("Promedio:");

        lbMaximo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMaximo.setText("Nota Maxima:");

        lbResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbResultado.setText("Resultado");

        salir.setBackground(new java.awt.Color(255, 0, 0));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Registro de estudiantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultado)
                            .addComponent(lbPromedio)
                            .addComponent(lbMaximo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tituloN2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titutoN1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tituloNombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(titutoEdad))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tituloN3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(limpiar)
                                            .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(SetCSV)
                                        .addGap(18, 18, 18)
                                        .addComponent(GetCSV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButtonCerrarLogin)
                        .addGap(18, 18, 18)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salir)
                    .addComponent(JButtonCerrarLogin)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titutoEdad)
                            .addComponent(tituloNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titutoN1)
                            .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloN2)
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloN3)
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calcular)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetCSV)
                            .addComponent(GetCSV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lbPromedio)
                .addGap(18, 18, 18)
                .addComponent(lbMaximo)
                .addGap(18, 18, 18)
                .addComponent(lbResultado)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private Estudiantes infoEstudiante() {
        String nombre = txtNombre.getText();
        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y espacios.");
            return null;
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre válido.");

        }
        int edad;
        try {
            edad = Integer.parseInt(SpinnerEdad.getValue().toString());
            if (edad <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese una edad válida mayor a 0.");
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese una edad válida mayor a 0.");
            return null;
        }

        double nota1 = Double.parseDouble(txtNota1.getText());
        double nota2 = Double.parseDouble(txtNota2.getText());
        double nota3 = Double.parseDouble(txtNota3.getText());

        if (nota1 < 0.0 || nota1 > 5.0
                || nota2 < 0.0 || nota2 > 5.0
                || nota3 < 0.0 || nota3 > 5.0) {

            JOptionPane.showMessageDialog(this, "Ingrese una nota válida 0.0 - 5.0");
        }

        Notas n1 = new Notas(nota1);
        Notas n2 = new Notas(nota2);
        Notas n3 = new Notas(nota3);

        Estudiantes estudiantes = new Estudiantes(nombre, edad);

        estudiantes.agregarNota(n1);

        estudiantes.agregarNota(n2);

        estudiantes.agregarNota(n3);

        return estudiantes;

    }

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            Estudiantes estudiante = infoEstudiante();   // obtengo del formulario
            if (estudiante != null) {
                registro.agregarEstudiantes(estudiante);     // lo guardo en el modelo
                ActualizarListaEstudiantes();                // refresco tabla
                JOptionPane.showMessageDialog(this, "Estudiante agregado correctamente.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar estudiante: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void SetCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetCSVActionPerformed
        // TODO add your handling code here:

        JFileChooser filechooser = new JFileChooser();
        int seleccion = filechooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = filechooser.getSelectedFile();
            try {
                ArchivoService archivoservice = new ArchivoService();

                List<Estudiantes> lista = archivoservice.CargarCsv(archivo);

                registro.ListarEstudiantes().clear();

                for (Estudiantes i : lista) {
                    registro.agregarEstudiantes(i);
                }

                ActualizarListaEstudiantes();
                JOptionPane.showMessageDialog(this, "Datos cargados correctamente.");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error al cargar archivo: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SetCSVActionPerformed

    private void GetCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCSVActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            try {
                List<Estudiantes> lista = registro.ListarEstudiantes(); //guardar csv
                ArchivoService archivoservice = new ArchivoService();

                archivoservice.GuardarCsv(lista, archivo);
                JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error al guardar archivo: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_GetCSVActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        Estudiantes estudiantes = infoEstudiante();
        lbPromedio.setText("Promedio: " + calculo.Promedio(estudiantes.getNotas()));

        lbMaximo.setText("Nota maxima: " + calculo.notaMaxima(estudiantes.getNotas()).getValor());

        double promedio = calculo.Promedio(estudiantes.getNotas());

        if (calculo.Aprobado(promedio)) {
            lbResultado.setText("Aprobado");
        } else {
            lbResultado.setText("Reprobado");
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void JButtonCerrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCerrarLoginActionPerformed
        // TODO add your handling code here:

        int confirmar = JOptionPane.showConfirmDialog(this,
            "¿Desea cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            this.dispose();

            // Abrir de nuevo el login
            LoginFrame login = new LoginFrame();
            login.setVisible(true);
        }

    }//GEN-LAST:event_JButtonCerrarLoginActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling  txtNombre.setText("");
        SpinnerEdad.setValue(0);
        txtNombre.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        lbPromedio.setText("");
        lbResultado.setText("");
        lbMaximo.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroEstudiantesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetCSV;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton JButtonCerrarLogin;
    private javax.swing.JTable JTabla;
    private javax.swing.JButton SetCSV;
    private javax.swing.JSpinner SpinnerEdad;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaximo;
    private javax.swing.JLabel lbPromedio;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JButton limpiar;
    private javax.swing.JButton salir;
    private javax.swing.JLabel tituloN2;
    private javax.swing.JLabel tituloN3;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel titutoEdad;
    private javax.swing.JLabel titutoN1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    // End of variables declaration//GEN-END:variables
}
